### ISSUE TITLE
Notebook Review

### ISSUE THREAD

**Issue by adelnehme** [datacamp/cleaning-data-in-r-live-training#1]
<p align="center">
<img src="https://cdn.datacamp.com/main-app/assets/brand/datacamp-horizontal-rgb-b641f95b7bdd7560b554c761a0b4910f9619907dd823c0e41244ed72078723bf.svg" alt = "DataCamp icon" width="95%">
</p>

Please read the key below to understand _how_ to respond to the feedback provided. Some items will require you to take action while others only need some thought. **During this round of feedback, each item with an associated checkbox is an action item that should be implemented before you submit your content for review.**
___
## Key

:wrench: This **must** be fixed during this round of review. This change is necessary to create a good **DataCamp** live training.

:mag: This wasn't exactly clear. This will need rephrasing or elaborating to fully and clearly convey your meaning.

📣  This is something you should take a look out for during the session and verbally explain once you arrive at this point. 

:star: Excellent work!
___

### General feedback

- [x] :wrench: **A.** Make sure all sections, sub-sections, sub-sub sections are formatted in **bold**.

- [x] :wrench: **B.** Can you format all Q&As like this please? 

```
---
<center><h1><b>Q&A</b></h1></center>
---
```
___

- [x] :wrench: **C.** Make sure to use `library(ggplot)` at the beginning. 

- [x] :wrench: **D.** Add more Q&A - here is the proposed outline: 

> - The Dataset
> - Diagnosing data cleaning problems
> - What we need to do
> - Q&A
> - Data type issues 
> - Q&A 
> - Text & categorical data issues
> - Q&A
> - ... till we reach Task 7 - treating the `last_review, reviews_per_month, avg_rating, avg_stays_per_month`
> - Q&A
> - Treating the `price` column
> - Treating duplicates
> - Q&A

- [x] 🔧 **E.** For the same of time and giving ample amount for Q&A - consider making the sanity checking section a homework where they come back to us with their answers. 

#### Diagnosing Data Cleaning Problems

- [x] :wrench: **1.** Since we are numbering tasks students will be going about in the data cleaning section, I recommend **not** using numbered lists for discussing 1) code descriptions (like when describing `head()` and `glimpse()` and 2) For observations on the dataset. For the latter, you can use the **"Observation 1:**... This is to make the notebook readable even without a voice-over happening. 

- [x] 🔧 **2.** This touches upon my feedback in 1, but the first 2 observations on `coordinates` and `last_review` / `listing_added` needing to be date types is numbered 3, 4 whereas it should be observation 1 and 2 respectively. 

- [x] 📣  **3.** I think this cell where you introduce tidyverse style of using pipe operators is actually a great opportunity to just clarify we will be mostly using this style moving forward. You can even add a small markdown cell just before clarifying what the tidyverse style is and that using the code below returns the same result, but we should use the tidyverse style because (insert your reasons) 

```R  
nrow(filter(airbnb, duplicated(listing_id)))
```

#### What we need to do

- [x] 🔧 **4.** Name them tasks 1, 2, 3 ... 

#### Data type issues - Task 1

- [x] 🔧 **5.** Make sure to add markdown with bullet points explaining the functions used in each code cell _(for both extraction of lat long - and it's addition into `airbnb`)_ - I think you need to pay attention as well to the use of the rename function (:mega: Potentially, you can showcases the results without rename then use rename to highlight it). 

- [ ] 🔧 **6.** At the end of the task, print the header of `airbnb` to showcase the change has been made.

#### Data type issues - Task 2

- [ ] 📣 **7.** This is a great time to say we're literally gonna use the same exact functions we used in the previous step `str_remove_all()` and `as.numeric()`.

#### Data type issues - Task 3

- [x] 🔧 **8.** Best to add markdown here explaining slightly the use of `as.Date(..., format = "") where `format` lets you choose the format and then introduce your (brilliant) table. 

- [ ] 🔧 **9.** Worth it to re-print the 2 columns being converted before the conversion and after the conversion to highlight the change.

#### Data type issues - Task 4

- [ ] 🔧 **10.** Worth it to re-print the column being split before the split and after the split to highlight the changes.

- [ ] 📣  **11.** Also probably worthwhile reminding students that we've seen the code used here in an earlier step. 

#### Data type issues - Task 5

- [x] 🔧 **11.** Make sure to add a bit of markdown explaining the use of `fct_collapse()` and `str_to_lower()`.

#### Data type issues - Task 6

- [ ] 📣 **12.** Good opportunity here to explain why this could potentially happen and on the domain knowledge need when cleaning data to identify what we need to do with it.

#### Data type issues - Task 7

- [ ] 📣 **13.** Essential to remind students of the earlier steps we did when identifying missing values while we were discovering the data, because at this time they probably forgot which exact columns had missing values. 

- [x] 🔧 **14.** I'd change the question of "Are the missing values related in any way?" to  relatively more elaborate 2-3 sentence explanation on the dynamics of missing data. For example "When dealing with missing data, it's important to understand what type of missingness we might have in our data. Oftentimes, missing data can be related to other dynamics in the datasets and requires some domain knowledge to deal with them."

- [x] 🔧 **15.** Add a `)` here: "(therefore have no ratings, reviews, or stays."

- [x] :star: **16.** Beautiful `is_visited` column

- [x] 📣 **17.** While treating `price` - great here to mention that we will use median because it is a better central measure than mean when there are outliers. Recommend writing that down in markdown as well between the cell where you plot box plots vs treat.

**Comment by matsuim** [comment]
@adelnehme Thanks for the great feedback (as always)!


**E.** Should I include the answers to the take-home questions in the solution notebook, or not?

**3.** Added the following in a cell. Let me know if this is too much text for the notebook.

> *A note on the `%>%` operator:*
> 
> This is an operator commonly used in the Tidyverse to make code more readable. The `%>%` takes the result of whatever is before it and inserts it as the first argument in the subsequent function.
> 
> We could do this exact same counting operation using the following, but the function calls aren't in the order they're being executed, which makes it difficult to understand what's going on. The `%>%` allows us to write the functions in the order that they're executed.
> ```r
> nrow(filter(airbnb, duplicated(listing_id)))
> ```

**General question** Do you have any recommendations for a good way of keeping track of talking points? I was just planning on making an annotated version of the solution notebook just for myself, but if you or anyone else has done something you think works well, I'd love to hear about it. There's also another layer to it that I'm concerned about which is how I'll be coding things out, since a fair amount of the code wasn't (and likely wouldn't be in a "real world" scenario) written out in the order it appears in the cell.  plan on doing a lot of intermediate steps showcasing, i.e. this is what the result looks like when you use a `group_by()` and a `mutate()`, but now we still have some extra stuff we need to do after this (but it's in the same series of pipes), or this is what happens when we don't specify this argument, and this is what happens when we do, etc.


**5.** Should I add a cell with descriptions of each new function used throughout the notebook? Or just for this particular cell?

**6, 9, 10** I don't have many explicit prints throughout the notebook since I was planning on walking through the code line by line, and then once we have the final result of that step, reassigning it using `airbnb <-`, so learners will see the output during the session, but it's not explicitly written in the notebook itself. Do you still think this is something I should add (it probably makes it easier to go back through, but I'm just worried about losing a lot of time by showing the same result twice for every re-assignment I do)?

**17.** Was definitely planning on doing this! Added to markdown as well.

**Comment by adelnehme** [comment]
Hi @matsuim :wave:

E. Not necessarily - I removed the solution from both student and solution notebooks.

5. That wouldn't be necessary - but if you want to add more, make sure they are in both solution and student notebooks.

General Question: Usually just having the solution notebook would be fine - especially since yours is currently well annotated (but if you want an even more detailed one, feel free to make it for the purposes of your session.) -- Also I'm a fan of showcasing intermediate steps to see what the output is in a series of steps of code - but don't feel like you have to do it at every juncture where that is the case (especially since we use group by and mutate quite a few times across different steps). 

17. I don't think we need to necessarily have dedicated code-cells to check out the output at each task, but as you go about your session, make sure to just show how your code achieved a certain result.
